create sequence hibernate_sequence start 1 increment 1;

create table article_tag
(
    article_id int8 not null,
    tag_id     int8 not null,
    primary key (article_id, tag_id)
);

create table articles
(
    id      int8 generated by default as identity,
    header  varchar(255),
    text    varchar(65535),
    user_id int8,
    primary key (id)
);

create table tags
(
    id  int8 generated by default as identity,
    tag varchar(255),
    primary key (id)
);

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table usr
(
    id       int8    not null,
    active   boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

alter table if exists article_tag
    add constraint article_tag_tag_fk foreign key (tag_id) references tags;

alter table if exists article_tag
    add constraint article_tag_article_fk foreign key (article_id) references articles;

alter table if exists articles
    add constraint article_user_fk foreign key (user_id) references usr;

alter table if exists user_role
    add constraint user_role_user_fk foreign key (user_id) references usr;